[package]
name = "uuidgen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4", features = ["derive"] }
uuid = { version = "1.7", features = ["v4"] }
log = "0.4"
env_logger = "0.11"

[profile.release]
lto = true      # Enable link-time optimization
panic = "abort" # Abort on panic instead of unwinding
